spring:
  datasource:
    url: jdbc:mysql://b7f6b104133831:781355ba@eu-cdbr-west-02.cleardb.net/heroku_54904c259d961d6?reconnect=true
    username: b7f6b104133831
    password: 781355ba
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false